trigger:
  - main

pool:
  vmImage: 'ubuntu-20.04'
  parallel: 1

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install Dependencies'

  - script: |
      npm run android
    displayName: 'Run Tests'

Make the above script single not parallel